[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
resolution = true
seeds = false
skip-lint = false

[programs.localnet]
wane_registry = "5Arj4zbFs5GigEGUSUb9hKNMYaPLqv1XgJXUcnGJ1wJH"
wane_vault = "5YK7gMzkjUvLaxfNisMdtjRK4UeAiJBCSonB3GgrtTYh"

[programs.devnet]
wane_registry = "5Arj4zbFs5GigEGUSUb9hKNMYaPLqv1XgJXUcnGJ1wJH"
wane_vault = "5YK7gMzkjUvLaxfNisMdtjRK4UeAiJBCSonB3GgrtTYh"

[programs.mainnet]
wane_registry = "5Arj4zbFs5GigEGUSUb9hKNMYaPLqv1XgJXUcnGJ1wJH"
wane_vault = "5YK7gMzkjUvLaxfNisMdtjRK4UeAiJBCSonB3GgrtTYh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"
